pipeline{
    agent any
    tools { 
        maven 'maven' 
        jdk 'java' 
    }
    stages {
       stage('code checkout') {
         steps {
            git branch: 'main', credentialsId:'github-token', url: 'https://github.com/jroua/microservice-application.git'
              }
        } 
      stage('create jar') {
         steps {
             sh ' cd product-service '
             sh ' mvn clean package '
              }
         }
      stage('build dockerfile') {
              steps {
               sh' docker build -t svc/product .'
             }
         }
       
    }
}
