pipeline{
    agent any
    tools { 
        maven 'maven' // nom de l'installation de maven dans jenkins ( maven 3.8.8 )
        jdk 'java' // nom de l'installation de java dans jenkins ( java 17 )
    }
    stages {
       stage('code checkout') {
         steps {
            git branch: 'main', credentialsId:'github-token', url: 'https://github.com/jroua/microservice-application.git'
              }
        } 
     stage('Merge main into prod') {
       steps {
        // Merge the "main" branch into "prod"
        script {
            sh 'git merge main'
        }
    }
     }
      stage('create jar') {
         steps {
             sh ' cd discovery-service && mvn clean && mvn package '
          //   sh ' mvn clean package '
              }
         }
      stage('build dockerfile') {
              steps {
               sh' docker build -t svc/discovery ./discovery-server '
             }
         }
       
    }
}
