# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
      
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build 
      run: | 
        docker build -t order-service:latest ./order-service
        docker build -t inventory-service:latest ./inventory-service
        docker build -t product-service:latest ./product-service
        docker build -t discovery-service:latest ./dicovery-service
        docker build -t api-gateway:latest ./api-gateway
    
    - name: Tag the image
      run: | 
        docker tag order-service:latest ${{ secrets.DOCKER_USERNAME }}/order-service
        docker tag inventory-service:latest ${{ secrets.DOCKER_USERNAME }}/inventory-service
        docker tag product-service:latest ${{ secrets.DOCKER_USERNAME }}/product-service
        docker tag discovery-service:latest ${{ secrets.DOCKER_USERNAME }}/discovery-service
        docker tag api-gateway:latest ${{ secrets.DOCKER_USERNAME }}/api-gateway
   
    - name: Docker Push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/order-service
        docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service
        docker push ${{ secrets.DOCKER_USERNAME }}/discovery-service
        docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway
